### ISSUE TITLE
Add setImmutable and isImmutable property to filestorage

### ISSUE THREAD

**Issue by kladkogex** [skalenetwork/skaled#1063]
**Is your feature request related to a problem? Please describe.**

NFTs require image and video files need to be immutable, because they need to exist forever.

Currently we do not have a way to set the file as immutable.

**Describe the solution you'd like**

1.  Owner of a file should be able to call setImmutable() to set the file as ummutable.

2. Once a file is set as immutable, no one should be able to unset.

3. Add isImmutable call to check if the file is ummutable.

**Comment by gannakulikova** [comment]
cannot be enabled immediately, need to be activated after particular timestamp/block number

**Comment by DmytroNazarenko** [comment]
[1.1.0-beta.2](https://github.com/skalenetwork/filestorage/releases/tag/1.1.0-beta.2)

**Comment by OleksanderSalamatov** [comment]
Approved on admin 2.4.0-beta.1
Cases on testrail: C922 & C923

**Comment by EvgeniyZZ** [comment]
Add result and correct version

**Comment by OleksanderSalamatov** [comment]
Approved on filestorage 1.1.0-beta.2
Cases on testrail: C922 & C923

Tested on chubby-alderamin chain

Result: 
1) setImmutable + isImmutable
setImmutable tx hash: 0x6415cfbc9f5cd577899ac4383b3ed3648ff461b494f81ba5cc2c3e28de887ad1
File set to be immutable
isImmutable result:
```
Name: storagePath, type: string: 1026467C91fdA40aCc7e6935d1E52f67274FD669/cat.png
2023-02-08 17:00:09,438 - cli.manager_client - INFO - Initializing ManagerClient, endpoint: http://52.39.199.187:10131
2023-02-08 17:00:09,450 - cli.manager_client - INFO - Executing function isImmutable on contract file_storage
2023-02-08 17:00:09,866 - __main__ - INFO - TRANSACTION_RESULT: True
```
File is immutable

2) Deletion of immutable file

Delete from schain owner key:
deleteFile tx hash: 0x46da82f65468ce777d0e862b86f6f991845cbc7af327d3f6ba6d48b2e696ead5
File is not deleted because of "`Error: File is immutable`"
Delete from regular key:
deleteFile tx hash: 0x5972678b3d831bac1ffefcf3d474cc201112e42bfa39d21e89170dadf2952b06
File is not deleted because of "`Error: File is immutable`"
